### ISSUE TITLE
Gossipping changed from 1 to 2

### ISSUE THREAD

**Issue by aletundo** [di-unipi-socc/FogMon#16]
Hello!

**2.0-tmp code**:
https://github.com/di-unipi-socc/FogMon/blob/606ecbc80c1053ee2f3fd39d32eeaa548e9ecf24/FogMon/src/leader/leader.cpp#L174

**Master code**:
https://github.com/di-unipi-socc/FogMon/blob/a274660f9fce3e984f1e63bb9c9df2790568d5c5/src/leader/leader.cpp#L132

[Paper](https://doi.org/10.1016/j.future.2020.08.011):

> Particularly, at every set interval of time, each Leader selects another random Leader and sends the complete report about its group of Followers.

I also had a look at the [latest paper about TLR5](https://doi.org/10.1016/j.future.2023.04.026) too see if there was an explanation for this change, but I wasn't able to find any mention.

Is it a regression bug or there's a reason for it that I'm not able to grasp by just reading the code?

Thanks!

**Comment by mrc-g** [comment]
That was added in the branch `2.0-liscio`. 
I don't remember adding it, it probably is one change I didn't properly document.
It should speed up the spread of information when the topology has many leaders (I think we reached 13 leaders in a LISCIO experiment).

**Comment by aletundo** [comment]
Alright! Thank you for the clarification.
